### ISSUE TITLE
Binary doesn't start on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by logix2** [srevinsaju/guiscrcpy#5]
The Linux binary downloaded from the guiscrcpy releases page (latest version) does not start on Ubuntu 18.04 LTS. This happens when I try to start it:

```
$ ./guiscrcpy-1.10-27082019-linux 

[4037] Error loading Python lib '/tmp/_MEIRHOerk/libpython3.7m.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/_MEIRHOerk/libpython3.7m.so.1.0)
```

**Comment by srevinsaju** [comment]
OK, that's a bug. Did you try with the source code? I compiled it on 19.04, so the compatibility is from that version onwards. Thanks for testing and finding vulnerabilities

**Comment by logix2** [comment]
I get an error trying to run it from source too:

```
$  python3 __main__.py
guiscrcpy v1.10.0-release
by srevinsaju
************************************
released on 24082019 GMT+0300 2048 
************************************
User configuration file not found!
output: <_io.BufferedReader name=18>
Traceback (most recent call last):
  File "__main__.py", line 1301, in <module>
    prog = MyApp(window)
  File "__main__.py", line 963, in __init__
    self.setupUi(MainWindow)
  File "/home/logix/guiscrcpy/mainui.py", line 110, in setupUi
    palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
AttributeError: type object 'QPalette' has no attribute 'PlaceholderText'
```

This is using the instructions from the readme.

Maybe you can compile the binary on something older, at least Ubuntu 18.04, so it has wider compatibility?

**Comment by srevinsaju** [comment]
I don't have Ubuntu 18.04, I will try it with a live CD.

**Comment by logix2** [comment]
You can also use it in a virtual machine.

**Comment by srevinsaju** [comment]
My PC is running Intel Core Duo 2, 2012 with no Vt-x. The reason I switch
to Linux 3months ago

>

**Comment by srevinsaju** [comment]
Yes, the binary error occurs on my device too, running Ubuntu 18.04 LTS. The rot cause is the native Python 3.6 as the interpreter. Hence Python 3.7 modules cannot be loaded onto the memory.

I shall compile another Linux version, using Python 3.6 modules.

However, the source code works perfectly, provided the up to date Python interpreter is used.

**Comment by logix2** [comment]
I just tried it, and the exact same error occurs when trying to run it from source on Ubuntu 19.04 too. And Ubuntu 19.04 has Python 3.7 by default.

**Comment by srevinsaju** [comment]
I have added another commit adding a variable called `dimension`, try running `python3 . ` after cloning the new source, and try again, hopefully, it should work. :)

**Comment by srevinsaju** [comment]
Is the binary working on 19.04?

**Comment by srevinsaju** [comment]
@logix2 please try the latest 18.04 specific release for guiscrcpy, put on the README.md file Download section. Please update with the outcomes.

Happy to help

**Comment by logix2** [comment]
Hi. 

> I have added another commit adding a variable called dimension, try running python3 . after cloning the new source, and try again, hopefully, it should work. :)

Running it from source still fails. This is on Ubuntu 19.04:

```
$ python3 .
guiscrcpy v1.10.0-release
by srevinsaju
************************************
released on 24082019 GMT+0300 2048 
************************************
User configuration file found!
cfg: ['#########################\n', 'Created by Srevin Saju\n', '#########################\n', '1567074229.4807978\n', '8000\n', 'None\n', 'False\n', 'False\n', 'False\n']
SUCCESS dispRO
Bitrate :  8000  + Dimensions None 
8000
dispRO: False

(python3:1262): Gtk-WARNING **: 12:54:05.439: Theme parsing error: gtk.css:1:114: Failed to import: Error opening file /home/logix/.local/share/gnome-shell/extensions/no-title-bar@franglais125.gmail.com/stylesheet.css: No such file or directory

(python3:1262): Gtk-WARNING **: 12:54:05.439: Theme parsing error: gtk.css:2:120: Failed to import: Error opening file /home/logix/.local/share/gnome-shell/extensions/no-title-bar@franglais125.gmail.com/stylesheet-tiled.css: No such file or directory
QApplication: invalid style override passed, ignoring it.
output: <_io.BufferedReader name=18>
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./__main__.py", line 1302, in <module>
    prog = MyApp(window)
  File "./__main__.py", line 964, in __init__
    self.setupUi(MainWindow)
  File "./mainui.py", line 110, in setupUi
    palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
AttributeError: type object 'QPalette' has no attribute 'PlaceholderText'
```

> Is the binary working on 19.04?

Yes.

> @logix2 please try the latest 18.04 specific release for guiscrcpy, put on the README.md file Download section. Please update with the outcomes.

This build works on Ubuntu 18.04, thank you!

**Comment by srevinsaju** [comment]
![Screenshot from 2019-08-29 15-48-22](https://user-images.githubusercontent.com/48695438/64028108-b79c4100-cb4a-11e9-975e-1199a439f75f.png)
This is the live example of running guiscrcpy from source on 18.04 LTS. I had no problem in installing so. 

As the binary works fine, I am removing the `bug` label, and might close this issue soon. It looks like there has been an unwanted extension on your gnome-shell, which is raising this error. Seems like https://extensions.gnome.org/extension/1267/no-title-bar/ had been creating the problems all day.

Please let me know, running from source, after disabling this gnome extension

**Comment by logix2** [comment]
That extension shows that output no matter what GUI app I launch from the command line, it's not related. And this issue is identical for me on both Ubuntu 19.04 (where I have that extension), and Ubuntu 18.04 (where I don't have that extension).

I'm just trying to make a blog post on my website https://www.linuxuprising.com about this scrcpy GUI which I find very interesting, but there are going to be users wanting to run it from source, that's why I want to see exactly how to do that... Maybe I have a missing dependency (which you forgot to mention in the readme) or something, given that it works for you?

**Comment by srevinsaju** [comment]
I am indeed interested in your blog and the website mentioned above. I apologise for the uncapability of me understanding your error, (I am 16, so..), but I have created a workaround for the above mentioned problem in the latest commit (today). Hopefully this fixes your error, and get the source running. The file from which the error is raised, is actually created automatically by pyuic5, a component of PyQt5 from the UI xml file. If this commit, helps to solve your problem, I am glad to help you out. In the case, this creates another problem, please put the output in this thread. I am grateful to be able to work with you.

**Comment by logix2** [comment]
You don't have to apologise for anything, bugs happen, don't worry about it. Using the latest Git works and I can now run it from source, thank you very much! I'll make a post about guiscrcpy on my blog probably tomorrow.

**Comment by srevinsaju** [comment]
It was indeed a new learning experience for me. Thank you very much :)

**Comment by logix2** [comment]
As promised, I wrote an [article on my blog about guiscrcpy](https://www.linuxuprising.com/2019/09/helper-gui-for-scrcpy-android-desktop.html). Thanks for this nice tool!
